name: Bug report
description: Report a reproducible problem
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for filing a bug. Please provide enough detail so we can reproduce it quickly.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened?
      placeholder: Short description of the bug
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Package version
      placeholder: e.g. 1.0.0
  - type: input
    id: python
    attributes:
      label: Python version
      placeholder: e.g. 3.11
  - type: textarea
    id: logs
    attributes:
      label: Logs or screenshots
      render: shell
