name: Security report (non-sensitive only)
description: Use this only for non-sensitive security hardening discussions
title: "[Security]: "
labels: ["security"]
body:
  - type: markdown
    attributes:
      value: |
        Do not submit exploit details or sensitive vulnerabilities here.
        For sensitive reports, use the Security tab private vulnerability reporting process in `SECURITY.md`.
  - type: textarea
    id: summary
    attributes:
      label: Security concern summary
      description: Non-sensitive description only.
    validations:
      required: true
  - type: textarea
    id: suggestion
    attributes:
      label: Suggested hardening improvement
